package com.hjn.dao;

import com.hjn.entity.SysAuthority;

public interface SysAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    int insert(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    SysAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuthority record);
}